name: Update TakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo Rtarun3606k/TakaTime \
          --pattern "taka-report-linux-amd64" \
          --output taka-report
          chmod +x taka-report

      - name: Run
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GIST_TOKEN: ${{ github.token }}
        run: export TARGET_REPO=${{ github.repository }} && echo "$TARGET_REPO" && ./taka-report -days=7 -bg "#2e3440" -text "#d8dee9" -subtext "#4c566a" -bar-bg "#3b4252" -c1 "#88c0d0" -c2 "#a3be8c" -c3 "#81a1c1" -c4 "#bf616a"
